#+TITLE: 1Q84
#+AUTHOR: "Haruki Marukami"
#+ROAM_TAGS: fiction
links: [[file:../org-roam/books.org][Books]] [[file:20200601-reading.org][Reading]]

* Main Characters
** Aomame
	 One of the two central characters, she is first introduced, in a cab listening to a piece of classical music.  The
	 music is repeated in the book. In the opening chapter she is "brought" to 1Q84
** Tengo
	 The other main character, a part time teacher at a cram school and wanabe writer.  He meets with Kamatsu who wants
	 him to re-write the novella "Air Chrysalis".
** Eriko Fukada
	 Writes the story "Air Chrysalis" which becomes ghost rewritten by Tengo. She is pecular, austic in a lot of
	 aspects. She is the daughter of the leader
** Kamatsu
	 Tengo's editor, he wants to become a star by releasing "Air Chrysalis".
** Dowager
	 Wealthy widow, who runs a battered women's shelter.  Employs Tamaru and Aomame.
** Tamaru
	 Bodyguard to the dowager, loyal to her, a friend to Aomame.
** Ushikawa
** The Leader
** Buzzcut and Ponytail

* Overview
  This novel is a question of what is reality, and how ones reality can change. The two main characters, meet as
  children and are hopelessly linked.  Early in the novel Aomame finds herself noticing things that have changed, the
  policeman and their weapons.  Tengo goes much longer before he sees the alternate reality.

* Thoughts
 Initial thoughts was is the book about two different conflicting moral delimenas. That of a killer of bad men, or
 someone who will be a ghostwriter to win an award.

 One thought that I had was the hope that the story Tengo is writing would be Aomame's story.  This didn't turn out to
 be the case.

 What is the significant of the cat story?

 Tengo's father.

 Besides the two moons being a sign of 1Q84,  what other significant role do they play?

* Vocabulary

* Quotes
- Don't let appearances fool you.  There is always only one reality.
  ( Spoken by the cab driver in the opening as Aomame gets ready to walk done the emergency stairs )

- There is nothing in this work that never takes a step outside a person's heart.
  ( Spoken by the leader to Aomame explaining how he knows what is driving her )

- He decided instead to imagine Sonny and Cher becoming good friends with the python pair on the ark.
	( Tengo -- I forget why I marked this, besides it is funny )

- They had come and gone, like vividly colored birds pearching momentarily on a branch before flying
  of somewhere.

- It's a distance that can't be measured. Like the distance that separates one persons heart form anothers.
   Tamaru

- The slightest difference in nuasce could bring the passage to life or kill it.
   Tengo - when re-writing Air Chrysalis

- He made jugdements instantaneuosly and carried them out decisively, unconcerned what other people
  might say. This was a quality indespensible to a brillant commanding officer, but it was a quality
  that Tengo himself did not possess.

- An omnious sandstorm was developing somewhere on the plane of his emotions.
