#+TITLE: LonesomeDove
#+AUTHOR: Larry McMurtry
#+ROAM_TAGS: fiction
links: [[file:20200601-reading.org][Reading]] [[file:books.org][Books]]

* Main Characters
	. Augustus McCrae aka Gus
	Is he likeable?  can be kind/compasionate, lazy, mean, instigator, violent.
	. Woodrow Call
	Is he likeable, cold, unemotional, troubled.
	. Lorena
	. Clara
	. Newt
  Call's son, though never recognized by Call.  Everyone could see it.
	. Deets
	. Dish
	. Jake Spoon
	  Is he a villian?
	. Blue Duck
    Obviously a villian
  . July Johnson
	. Elmira
	  Runs away from July leaving a child when she is pregant with July's child.

* Overview
* Thoughts
	What is he saying about relationships?
	 Women in particular - Lorena, Maggie, (The woman that rapes Roscoe), Clara ( Is she ever in the story ), Elmira

  Kids/Inexperience Dying
	   The first two hired hands to die are youngester, the first to water mocassins, the second to lightening, no
		 fault of theirs.  The murder at the hands of Blue Duck are different,  however the theme of
	   being unprepared seems to be high. Who is responsible?  Call/Gus/Jake/Fate?

* Writing Examples
** Call's thoughts
	 "He had ignored the claim, and the woman died, but somehow the claim remained, like a weight he
	 had to carry forever."  Chpt 46

	 "Listening to men talk usually made him feel more alone than if he were a mile away by himself
	 under a tree."

** Pea Eye
	 "..the thought of women entered his head all on its own, and once it came it usually tent to stay
	 for several hours, filling his noggin like a cloud of gnats.  Of course a cloud of gnats was
	 nothing in comparison to a cloud of Gulf Coast mosquitoes."

** Random
   Ought don't count for as much as a gnat, whey you're talking about love.  -Probaly Clara

	 Looking at her was like looking at the hills. The hills stayed as they were. You could go to
	 them, if you had the means, but they extended no greeting.
* Vocabulary
	. chaparal
	. quirt
	. vaquero
