#+TITLE: OldInArtSchool
#+AUTHOR: Nell Painter
#+ROAM_TAGS: non-fiction
links: [[file:20200601-reading.org][Reading]] [[file:books.org][Books]]

* Synopsys
A memoir of an older (64) African-American who decides to go back to school to become and artist.
It chronicles her time from undergraduate school, through grad school and beyond. A lot of the book
focuses on what it means to be an African-American in society.

The book takes place in the 2004-2012 time frame.

* Overview
Enjoyed reading the book, it caused me to think about how African-Americans with themselves as
separate from Americans.  Often she would feel that her instructors wouldn't understand where she
was coming from or what her art was trying to do since she was African-American. At times it felt
like she was using the difference as a crutch or an excuse.  Her instructors approved of her work
after she spent a summer, in the Andirondacks, improving her skills.

Her pre-art carrer was as a promient History Professor (Princeton)  and writer, mostly on racial relations. Her
book "The History of White People" is highly regarded, it won her fame, front page NY Times, Stephen
Colbert, etc..   At times she struggled to fully commit to being an art student. At time she has an
air of entilement, she had huge benefits, though earned through hard work, that most people will
never have.  I don't remember her ever calling it that, or even acknowledging it.

A sub-plot was the care and death of her parents, her dads suffered from server depression,
possibly brought on by the sickness of his wife.   The mom dies first and the dad becomes more
needy.  She was honest about her emotions dealing with the dad, wishes he would have died first.
Didn't seem overly empathetic to him.

* Quotes (paraphrasing)
- African art stops being include in Art history after the Egyptian Period
- There are only Berliners,  her replay was ask that to a black Berliner.


"I have to take my own advice and shoulder my armanent every single day.  Every single day, not only
to close thge eyes of disparagement, but also to stop my ears against adulation.  Not to see myself
through other peoples eyes. To remain what gurus call `centered.`  Nell Painter
