#+TITLE: ReverenceForWood
#+AUTHOR: Eric Sloan
#+ROAM_TAGS: non-fiction
links:
Date Read:
* Synopsys
The early history and success of America was largely do to the abundance of natural resource,  and
not least of which was wood.  Wood was so importatant that early maps and coins bore trees.  A lot
of what had been known was lost do to the industrial revelovution post civil war.

Knowledge of growing orchards of different tree types, medicinal properties of different species or
even leaves vs bark.

* Overview
The first part talked about the information that was gleaned from tearing down an old barn, and how
the early Americans, 18th century, new a lot of wood movement and how to use the wood properly.
Which woods were used where.

The second talked about all the uses for wood, and how the settlers new how to use the different
species for highest benefit, and which species were of lower value, hickory was one of the highest
regarded species.

There was talk of over harvesting, even at that point.  England, who would buy American timber had
depleted their supply of trees a long time agao.

* Ideas to explore
** People
   - Verrazano Early settle, pre Plymouth Plantaion
   - Cartier Another early settler ( Ship Captain)
** Dudleytown Ct
** Seek-no-further apples

* Facts
** Pocahontas died in London 1617
** Squanto was educated in London
** Samoset greeted Cpt John Smith in English.
** Sassafras was extremely important early on
