#+TITLE: RunningWithScissors
#+AUTHOR: Augusten Burroughs
#+ROAM_TAGS: non-fiction
links: [[file:20200601-reading.org][Reading]] [[file:20201220-2020books.org][2020Books]] [[file:20210107-memoir.org][memoir]]

* Overview
Memoir about Augusten childhood as he becomes a writer.  It tells the story of being sent to live
with his mother's therapist.

* Characters
	. Augusten
	. Dr Finch - Crazy Therapist
	. Hope - Daughter how takes Augusten under her wing
	. Natalie - Another daughter, becomes best friends
	. Neil - 30 year old former patient (adopted child) that becomes Augusten (lover/rapist)

* Thoughts
I found this difficult partially because it was hard to imagine how this could have happened in our
society.  The main part of the book takes place in the early 80s.  The disfunction of the Finch
family, the allowing of child rape, homosexual rape as well as the general squalor that they lived
in.

The book's main redeeming value is that Augusten survives through it all.

The story is well written the scenes are funny.

I read the book because it was recommended by a couple of climbing friends, Randy and Chris, and I
thought it was a "coming out" story.  The main character is a homosexual but that isn't the main
point of the story but how he survived in didn't let his world destroy him.
